apiVersion: v1
kind: PersistentVolume
metadata:
  name: localpersist
  labels:
    type: localpersist
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /meubanco/
